### ISSUE TITLE
Getting ECONNRESET after a long time.

### ISSUE THREAD

**Issue by dharshanduck** [microsoftgraph/security-api-solutions#11]
# Getting ECONNRESET after a long time

The script runs for aproximately 2 hours, and manages to send some data over to Azure Sentinel (not all though), however right at the 2 hours mark, the script fails and I get the error as pasted below.

# Additional Info
Security-api-solutions/Samples/MISP is the repo where this error is occouring.

# General

## Error Log

Traceback (most recent call last):
  File "script.py", line 99, in <module>
    main()
  File "script.py", line 95, in main
    request_manager.handle_indicator(request_body)
  File "/home/misp/microsoftsentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 174, in handle_indicator
    self._update_headers_if_expired()
  File "/home/misp/microsoftsentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 189, in _update_headers_if_expired
    config.graph_auth[CLIENT_SECRET])
  File "/home/misp/microsoftsentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 71, in _get_access_token
    data=data
  File "/home/misp/.local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/misp/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/misp/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/misp/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/misp/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))

**Comment by bz38** [comment]
The codes here refresh the access token every hour since the access token is only valid for 1 hour. Since you mentioned that this issue happened at the 2-hour mark, the codes were able to get the access token 2 times and the issue was encountered the third time it tries to get the access token.

OS Error 104 means "Connection reset by peer". (http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html)

This means the issue is on the server side. (https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean). @edwardkoval Can you check the server log for me and see what may have been causing the issue?

**Comment by bz38** [comment]
Also, I tried stress testing the Microsoft OAuth. The issue was not caused by the system being stressed.

**Comment by dharshanduck** [comment]
I am still experiencing the issue, and there seems to be no resolution, any reason this is now closed?

**Comment by dharshanduck** [comment]
Looking for updates on your end

**Comment by bz38** [comment]
@dharshanduck Did you encounter this issue just once? Have you tried again after the first time you encountered this issue?

**Comment by dharshanduck** [comment]
@bz38 this issue happens exactly as stated above every time i run the script

**Comment by bz38** [comment]
> @bz38 this issue happens exactly as stated above every time i run the script

**Comment by bz38** [comment]
> @bz38 this issue happens exactly as stated above every time i run the script

@dharshanduck Does this happen every time at the 2-hour mark. I suspect your request could be blocked for some reason.

@edwardkoval Would you be able to take a look at the server log and see if my suspicion is true?

**Comment by dharshanduck** [comment]
@bz38 The weird thing is, i am getting logs at Sentinel, yet it always econnreset at the 2 hour mark, so i doubt the request could be blocked. As indicators are being sent over, and im able to see it in the logs on sentinel

**Comment by dharshanduck** [comment]
@bz38 ermm ??

**Comment by dharshanduck** [comment]
@bz38

**Comment by preetikr** [comment]
Closing this thread due to inactivity - please re-activate with specific request if not applicable.

**Comment by OlivierCuyp** [comment]
@dharshanduck I got a work getting the same kind of issue.
Did you find a solution ?
I felt on this article:

https://blog.mastykarz.nl/econnreset-error-connecting-office-365-nodejs/

Problem seems to be linked to  the SSL certificate used on Office 365...

**Comment by rahulshaw6** [comment]
@OlivierCuyp did that article solve your issue? Which library are you using for making the api calls to microsoft ?

**Comment by OlivierCuyp** [comment]
@rahulshaw6  I didn't test it, instead I implemented a watch dog which kill the process if it hangs for too long (5 min). Since I'm in Docker the process(container) is then restarted automatically.
I'm using the official [JS Microsoft Client](https://github.com/microsoftgraph/msgraph-sdk-javascript).

**Comment by OlivierCuyp** [comment]
@rahulshaw6 with the  watchdog, I also added some more logs.
To give a bit of context, the application is poller several mailboxes.
Here is what I see:

...
- getEmails(mailbox1) >> ECONNRESET // Error catch, worker logs & continues with the next mailbox
- getEmails(mailbox2) >> OK
- getEmails(mailbox3) >> OK
- getEmails(mailbox1) >> CUSTOM_WATCHDOG_HANG_ERROR // process is hanging and is killed

It always first an ECONNRESET and then when retrying on the same mailbox (being mailbox1, mailbox2 or mailbox3).
It seems that the mailbox resource doesn't reply at all after an ECONNRESET...

Please, let me know if you have findings on your side. I want to understand what happens here.
