### ISSUE TITLE
You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by lanslote** [microsoftgraph/security-api-solutions#3]
# Issue Title
You cannot call a method on a null-valued expression

* If you find bugs in the current samples or documentation requests or bugs file issues in the respective [sample repository](sample-repos.md).
* If you have new sample requests or issues that is not scoped to a single sample, file issue adhering to the following template.

Provide a descriptive title.
When I try to execute ".\Get_Security_Alerts.ps1"
Error occurs like below.

=========================
```shell
PS C:\Users\jechoi\Documents\GitHub\security-api-solutions\Samples\PowerShell> .\Get_Security_Alerts.ps1

You cannot call a method on a null-valued expression.
At C:\Users\jechoi\Documents\GitHub\security-api-solutions\Samples\PowerShell\Get_Security_Alerts.ps1:150 char:9
+         $errorResponse = $ex.Response.GetResponseStream()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
=========================

What can I do for checking ?

# Additional Info

Provide the sample repo names which have the issue for sample related issues not scoped to one repo. Alternatively, provide link to the article that needs content update.

# General

Provide details on the problem you are experiencing, including step by step instructions to reproduce the issue.

Please provide a code snippet for your issue if it is relevant, either inline, link to a gist (or similar) or as a zipped attachment.

For UI problems please provide screenshots inline or as a zipped attachment.

**Comment by edwardkoval** [comment]
@lanslote which version of PowerShell are you using?

**Comment by preetikr** [comment]
Closing this thread due to inactivity - please re-activate with information requested to investigate further. Thanks.
