### ISSUE TITLE
Using security graph api to create alert

### ISSUE THREAD

**Issue by anthonylamark** [microsoftgraph/security-api-solutions#32]
# Using security graph api to create alert

If a third party security product wants "to generate" (create) an alert, how is this done?
Thanks very much.

**Comment by chinguyen1** [comment]
@anthonylamark Security alerts are supplied by Microsoft security providers such as Office 365, Azure Security Center, etc. We cannot directly create an alert. However, you can create a [Threat Intelligence Indicator](https://docs.microsoft.com/en-us/graph/api/tiindicators-post?view=graph-rest-beta&tabs=http) with **action** as **alert** to Azure Sentinel or Microsoft Defender ATP for further investigation.
