### ISSUE TITLE
PATCH of security alert from Defender ATP sends response with old data

### ISSUE THREAD

**Issue by tmanOC** [microsoftgraph/security-api-solutions#33]
# PATCH of security alert from Defender ATP sends incorrect response

When I send a request to patch a security alert generated from Defender ATP using an application Bearer token, It returns success, but the body of the response is that of the alert before the change.

# Additional Info
Request data:
```
PATCH https://graph.microsoft.com/v1.0/security/alerts/{alert-id}
headers: {"Prefer":"return=representation"}
body: {
"vendorInformation":{
"provider":"Microsoft Defender ATP",
"vendor":"Microsoft"
},
"status":"unknown"
}
```
Response returns the old status:
```
200
{
...
"status":"inProgress",
...
}
```

If I send the identical request again, the response looks right, but I assume that's because I actually changed it with the first request.

**Comment by tmanOC** [comment]
It appears this works correctly some of the time. But it normally sends the incorrect response when I change something. The last time I checked, for Defender ATP alerts only "feedback", "status" and "assignedTo" may be changed.

**Comment by chinguyen1** [comment]
@tmanOC For PATCH alert, please make sure all the properties need to be camel case in the request body. If the issue still persists, please send us your tenantId and appId with detail of the Patch request, and we will help further investigate the issue.
