### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Castaldio86** [microsoftgraph/security-api-solutions#45]
/var/www/MISP/venv/bin/python3 script.py
fetching & parsing data from misp...
Traceback (most recent call last):
  File "script.py", line 100, in <module>
    main()
  File "script.py", line 69, in main
    events = _get_events()
  File "script.py", line 18, in _get_events
    for event_filter in config.misp_event_filters
  File "script.py", line 18, in <listcomp>
    for event_filter in config.misp_event_filters
TypeError: list indices must be integers or slices, not str

#####

config.py

graph_auth = {
    'tenant': '%SNIP',
    'client_id': '%SNIP',
    'client_secret': '%SNIP',
}
targetProduct = 'Azure Sentinel'
misp_event_filters = [
    {
        "last": '1h'
    }
]
action = 'Alert'
passiveOnly = False
days_to_expire = 1
misp_key = '%SNIP'
misp_domain = '%SNIP'
misp_verifycert = True

**Comment by chinguyen1** [comment]
@Castaldio86 , can you please share a screenshot of the error from the terminal when you ran script.py? Were you able to find the threat intelligence indicator you tried to push in Azure Sentinel logs after running the command? Also, if possible, please share the tiIndicator (sanitized) you're trying to push in MISP events.

**Comment by Castaldio86** [comment]
![image](https://user-images.githubusercontent.com/12892740/77231520-c9ebd400-6b9b-11ea-9304-77c036098b9c.png)

@chinguyen1 I'm stuck at the very beginning. The script is having issues with  _get_events()

**Comment by Deceitfulone** [comment]
I have the exact same issue as this. I built a new Misp server and connected the script to it so it. I have never used the tool before so its a good chance I'm doing something wrong.

**Comment by chinguyen1** [comment]
@Castaldio86 @Deceitfulone , the issue is likely with the format of at least one of the fields of your events you are trying to push. The config.misp_event_filters is a list and event_filter is a dictionary. Would you be able to use the Debugger to debug the steps in Get_Event() to see the events?

**Comment by Castaldio86** [comment]
@chinguyen1 I think i can find some to help. 

If I create a dict instead of a list in config.misp_event_filters I get a different error.

![image](https://user-images.githubusercontent.com/12892740/77559874-03cf1a00-6ebd-11ea-8d7a-73391512445f.png)

![image](https://user-images.githubusercontent.com/12892740/77560077-3c6ef380-6ebd-11ea-9d77-7c56923ad806.png)

**Comment by intatest2** [comment]
I am having the same issue as well. Did someone figure out how to fix it? Thanks - Sak
![image](https://user-images.githubusercontent.com/61676285/77597002-43434800-6f49-11ea-8ac6-7ba4c8d8e930.png)

**Comment by chinguyen1** [comment]
@Castaldio86 Originally you had your misp_event_filters as a list, so that should be fine. However, I think your event is where it might have caused the issue and please let us know when you are able to debug to get the events.

**Comment by intatest2** [comment]
@chinguyen1 , here is the debug info. Hope this helps, 

![image](https://user-images.githubusercontent.com/61676285/77975462-74eb5300-733d-11ea-99d3-9b98bb14a46e.png)

**Comment by chinguyen1** [comment]
@intatest2 Thank you for providing your debug info. It still doesn't really provide much more details for our investigation. Would you mind sending a message to us at graphsecfeedback@microsoft.com with this Github issue link, and we can possibly set up a call to debug this? Thanks.

**Comment by intatest2** [comment]
@chinguyen1 Will do. Thanks.

**Comment by bsapuletty** [comment]
I have the exact same issue as this. Please let me know the outcome of the session

**Comment by chinguyen1** [comment]
We've found the issue and are working to fix the bug. Thanks for bringing it to our attention.

**Comment by chinguyen1** [comment]
The bug has been resolved. Please note that we've updated the list of filters in Readme.md, and included code update in config.py and script.py files. Please clone the latest MISP repo, give it a try again, and let us know if it works for you. Thank you all for your patience while we worked on fixing this.

**Comment by chinguyen1** [comment]
Closed the issue. Please reopen it if you have any related questions.
