### ISSUE TITLE
keyword for vendorInformation

### ISSUE THREAD

**Issue by josephka3** [microsoftgraph/security-api-solutions#47]
# Issue Title
keyword for vendorInformation

Provide a descriptive title.
In the OData Filter to filter by product, we need to use a filter like "vendorInformation/provider eq 'ASC' ", is there a documented list of the keywords of the product names to be used. I was searching for what I should use for Azure Sentinel, I guess it might be "ASI" but not sure. Can you please point me to where this is documented for other products like Defender ATP.

# Additional Info

Provide the sample repo names which have the issue for sample related issues not scoped to one repo. Alternatively, provide link to the article that needs content update.

# General

Provide details on the problem you are experiencing, including step by step instructions to reproduce the issue.

Please provide a code snippet for your issue if it is relevant, either inline, link to a gist (or similar) or as a zipped attachment.

For UI problems please provide screenshots inline or as a zipped attachment.

**Comment by chinguyen1** [comment]
@josephka3, you can run this query on [Graph Explorer](aka.ms/ge) to get a list of alert providers you've subscribed to. Let us know if this works for you.
https://graph.microsoft.com/v1.0/security/alerts?$top=1&$select=vendorInformation

**Comment by josephka3** [comment]
Thank you for the reply, I understand we can query the alerts using the api and see the vendorinformation field.
I was just hoping if this information is available as a standard document in a clear table.
_Ex:_,
**Product                                   Keyword**
Azure Security Center                 ASC
Azure Sentinel                             ASI
Defender ATP ....                          
...
It would be useful to standardize the security api usage.

**Comment by chinguyen1** [comment]
Thank you for your suggestion. We are looking to include them in the documentation.

**Comment by josephka3** [comment]
@chinguyen1 Just a thought, wouldn't it be appropriate to close this issue after we have this documented.

**Comment by chinguyen1** [comment]
@josephka3 the $filter keywords should now be available on this [documentation](https://docs.microsoft.com/en-us/graph/api/alert-list?view=graph-rest-1.0&tabs=http). Let us know if you have any other questions or feedback.

**Comment by josephka3** [comment]
thanks a lot @chinguyen1 ,looks perfect.
