### ISSUE TITLE
howto guide to add new provider to security api

### ISSUE THREAD

**Issue by haimmag** [microsoftgraph/security-api-solutions#51]
we need sample code and guide on how to build and deploy  custom provider to graph security api
we need to integrate our alerts and insights to security api

**Comment by chinguyen1** [comment]
@haimmag To build and deploy custom provider to Microsoft Graph Security API, please contact us at: graphsecfeedback@microsoft.com. Thank you.

**Comment by chinguyen1** [comment]
Closing this as you've contacted us via email.

**Comment by haimmag** [comment]
our company product need to integrate our security product with graph
security api as a provider (like Azure Sentinel )

https://docs.microsoft.com/en-us/graph/security-partner-overview
we need guide on how to:
Enable others to integrate with our products through the Microsoft Graph
Security API.
Alerts from our security products.

*code samples and step b step guide*.
