### ISSUE TITLE
Script error when schema expecting string but receiving int from MISP IOC entry

### ISSUE THREAD

**Issue by cneitaGit** [microsoftgraph/security-api-solutions#52]
**Script error when schema expecting string but receiving int from MISP IOC entry**

We seem to be experiencing an issue with the script whenever a MISP IOC entry in the database has a different value type than the MS sciprt schema is expecting. An example of this is receiving a int when the script is expecting a string. As a resulting the script immediately errors and stops running. Is there any way to jump over/ignore these IOC entries and have the script still continue to run?

**Comment by chinguyen1** [comment]
@cneitaGit To help us investigate this issue, can you please provide a screenshot of the error when running the script?

**Comment by chinguyen1** [comment]
@cneitaGit We've made some update to MISP scripts. Please git pull the repo and give it another try. Let us know if you still run into any issues or have any questions.

**Comment by chinguyen1** [comment]
@cneitaGit Has the update script worked for you as expected? If it's resolved, we'll close the issue.

**Comment by cneitaGit** [comment]
@chinguyen1 
Thank you for the update. After pulling the updates and running, the script seems to send the command line into a unresponsive mode several times before completing but not exiting the script on completion. After completion the script is stuck on the following screen:
  
![image](https://user-images.githubusercontent.com/61124724/83118447-446a3000-a0c6-11ea-97ad-c753f8cd4425.png)

**Comment by chinguyen1** [comment]
@cneitaGit The script exits as expected on my end. The reason it took a bit longer as it now can log data to the Logs. After the script finished running and you checked the results, were all the IoCs sent to Azure Sentinel as expected?

**Comment by chinguyen1** [comment]
Please reopen the issue if the issue still persists.
