### ISSUE TITLE
Python_QuickStart.py - Returns 400 on create_ti

### ISSUE THREAD

**Issue by eCrimeLabs** [microsoftgraph/security-api-solutions#54]
# Python_QuickStart.py returns 400 error code on Create TI IOC

I've downloaded the project and working on the Python_QuickStart.py where I've added
- appId
- appSecret
- tenantId

I created the "API" access as described in this page from CIRCL https://www.circl.lu/doc/misp/connectors/#misp-to-microsoft-graph-security-script

I know that this if for the MISP <-> Microsoft Graph integration however I suspect the API setup on Microsoft Azure side should be the same.

I then uncommented the "create_ti" data model:
```
data = {
    "action": "alert",
    "activityGroupNames": [],
    "confidence": 0,
    "description": "This is a canary indicator for demo purpose. Take no action on any observables set in this indicator.",
    "expirationDateTime": "2020-12-31T21:43:37.5031462+00:00",
    "externalId": "Test--123456",
    "fileHashType": "sha256",
    "fileHashValue": "aa64428620b57bf51524d1756b2ed746e5a3f31b67cf7fe5b5d8a9daf07ca313",
    "killChain": [],
    "malwareFamilyNames": [],
    "severity": 0,
    "tags": [],
    "targetProduct": "Microsoft Defender ATP",
    "threatType": "WatchList",
    "tlpLevel": "green"
}
```

Issue is that I'm getting a 400 error code in return on the post.

When using the 'make_request' in the same code 

```
GET "https://graph.microsoft.com/beta/security/tiIndicators"

Headers :
{
    "Content-Type": "application/json",
    "Accept": "application/json",
    "Authorization": "Bearer ..."
}
########################################################################################

Response :
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#Security/tiIndicators",
    "value": []
}

########################################################################################
```

Hope you can assist in identifying where the problem might be located.

**Comment by chinguyen1** [comment]
@eCrimeLabs Have you entered your application ID, app Secret, and tenant ID info from line 15-17 in the script? The credentials are needed to call the Graph Security API.

**Comment by eCrimeLabs** [comment]
Hey there,

Yes these are added, there could be an indication that there is a generic issue with the Graph Security API as I also tested with the Graph Security Explorer and the API returning 400 Errors when POST are done to the API.

So I've tested both with the MISP integration following the guidelines as well with https://developer.microsoft.com/en-us/graph/graph-explorer both seems to be failing, and have consented to the permissions in there as well :)

I'm using the test case example "create TI indicator (beta)"

Bad Request - 400 - 518ms
```
{
    "error": {
        "code": "",
        "message": "",
        "innerError": {
            "request-id": "0fb4cbc8-04ac-4ce4-8547-0eccdc6310d5",
            "date": "2020-05-26T17:53:18"
        }
    }
}
```

**Comment by chinguyen1** [comment]
@eCrimeLabs I've just tested Graph Explorer & Python scripts, they all work fine, so I know there isn't a generic issue with the Graph Security API. It might be a permissions issue with your app. Are you using App-only or User-delegated mode for your app? 
If it's User Delegated, please make sure the user is a member of an Azure AD Limited Admin role - either Security Reader or Security Administrator - in addition to the application having been granted the required permissions. Please refer to [authorization for Graph Security API ](https://docs.microsoft.com/en-us/graph/security-authorization) documentation for more information on this.

**Comment by eCrimeLabs** [comment]
So I switched to the Python_QuickStart sample to keep it as simple as possible

As far as I can read When getting data from Graph it is OK, but when trying to create it fails, 
as the error indicates that it could be a permission issue, I followed the documentation "App Registration"
under https://github.com/microsoftgraph/security-api-solutions/tree/master/Samples/MISP

The permission is set to "ThreatIndicators.ReadWrite.OwnedBy" and status is "Granted" under the App Registrations

The following are set:
- appId
- appSecret
- tenantId

GET  tiIndicators returns HTTP Status Code 206
POST tiIndicators returns HTTP Status Code 400

Are there any other elements or permissions the python code need on the Azure side to autenticate

The below is the output when executing the example code

```
File Python_QuickStart.py saved
root@private:/opt/security-api-solutions/QuickStarts/Python# PYTHONHASHSEED=0 python3 Python_QuickStart.py
Access token acquired.
Sample Microsoft Graph Security API code loaded

########################################################################################
Calling the Microsoft Graph Security API...

GET "https://graph.microsoft.com/beta/security/tiIndicators"

Headers :
{
    "Authorization": "Bearer <REDACTED>",
    "Content-Type": "application/json",
    "Accept": "application/json"
}
########################################################################################
Response : Status Code 206

Response :
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#Security/tiIndicators",
    "value": []
}

########################################################################################
Calling the Microsoft Graph Security API...

CREATE "https://graph.microsoft.com/beta/security/tiIndicators"

Headers :
{
    "Authorization": "Bearer <REDACTED>",
    "Content-Type": "application/json",
    "Accept": "application/json"
}

Body :
{
    "targetProduct": "Microsoft Defender ATP",
    "tags": [],
    "description": "This is a canary indicator for demo purpose. Take no action on any observables set in this indicator.",
    "threatType": "WatchList",
    "fileHashType": "sha256",
    "confidence": 0,
    "malwareFamilyNames": [],
    "tlpLevel": "green",
    "expirationDateTime": "2020-12-31T21:43:37.5031462+00:00",
    "fileHashValue": "aa64428620b57bf51524d1756b2ed746e5a3f31b67cf7fe5b5d8a9daf07ca313",
    "action": "alert",
    "killChain": [],
    "severity": 0,
    "externalId": "Test--123456",
    "activityGroupNames": []
}
########################################################################################

Response : Status Code 400
('{\r\n'
 '  "error": {\r\n'
 '    "code": "",\r\n'
 '    "message": "Http request failed with statusCode=Unauthorized; ",\r\n'
 '    "innerError": {\r\n'
 '      "request-id": "a9e509a2-bfd2-4f93-aa45-1f1e9f28f3de",\r\n'
 '      "date": "2020-05-26T20:28:47"\r\n'
 '    }\r\n'
 '  }\r\n'
 '}')

```

**Comment by chinguyen1** [comment]
@eCrimeLabs please send your app ID and tenant ID to our alias: graphsecfeedback@microsoft.com, so we can take a closer look in your API call in our logs. Thanks.

**Comment by eCrimeLabs** [comment]
Thanks @chinguyen1 I've send a mail with the information

**Comment by chinguyen1** [comment]
Thanks for sending the info, @eCrimeLabs. I'm looking into our logs.

**Comment by chinguyen1** [comment]
@eCrimeLabs As mentioned in our email thread, please make sure your MDATP subscription is active to be able to post the threat indicators.

**Comment by chinguyen1** [comment]
Please reopen the issue if you have any other issues/questions.
