### ISSUE TITLE
Cloud App Security Alert Status not change in GUI upon PATCH

### ISSUE THREAD

**Issue by tlschoenfeld** [microsoftgraph/security-api-solutions#60]
I am setting up an "Automated Process" to gather alerts using GRAPH API, but once i run the PATCH, the GUI will not recognize the change and clear the alert.  When I run a GET, I see that the status has been updated to resolved.

Using Powershell.

Code is below, i have removed client and tenant Info

`$clientId = "APP ID"
$clientSecret = "APP SECRET"
$tenant = "TENANT DOMAIN NAME"
$date = get-date
$login = "https://login.microsoft.com"
$api = "https://graph.microsoft.com"
$ResolveJson = '{"status":  "resolved","vendorInformation": {"provider":  "IPC","providerVersion":  null,"subProvider":  null,"vendor":  "Microsoft"}}' | ConvertFrom-Json | ConvertTo-Json

$body = @{ grant_type = "client_credentials"; resource = $api; client_id = $clientId; client_secret = $clientSecret }

$uri = "https://graph.microsoft.com/v1.0/security/alerts/"

$oauth = Invoke-RestMethod -Method Post -Uri $login/$tenant/oauth2/token?api-version=1.0 -Body $body -ErrorAction SilentlyContinue

$header = @{ 'Authorization' = "$($oauth.token_type) $($oauth.access_token)" }

$URINEW = $uri
$results = @()
DO{

	
	$value = Invoke-RestMethod -Headers $header -Method GET -Uri $urinew 
	$count += $value.value.count
	$valueDATA = ($value.value | ? { $_.category -eq "LeakedCredentials" })
	foreach ($event in $valueDATA)
	{
		
		$results += $EVENT
		
	}
	$uriNEW = $value.'@odata.nextLink'
	
}WHILE ($count -lt 5900)

FOREACH($alert in $results){
$urinew =  "https://graph.microsoft.com/v1.0/security/alerts/" + $alert.id

Invoke-RestMethod -Headers $header -Method patch -Uri $urinew -Body $bodyjson -ContentType "application/json"
}
`

**Comment by brittanydrandolph** [comment]
Thanks for your feedback. While the Microsoft Cloud App Security does support Patch Alert status, when a user is updating an alert through the Graph Security API then this updated status will only reflect on apps that integrate with Graph Security API, but currently not on MCAS portal. However, we are working on landing this feature. You can learn more about the different types of alerts from this [link](https://docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-1.0).

**Comment by tlschoenfeld** [comment]
> Thanks for your feedback. While the Microsoft Cloud App Security does support Patch Alert status, when a user is updating an alert through the Graph Security API then this updated status will only reflect on apps that integrate with Graph Security API, but currently not on MCAS portal. However, we are working on landing this feature. You can learn more about the different types of alerts from this [link](https://docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-1.0).

Thank you!
